//! Restore-side artifacts.
//!
//! The script is deliberately *data-driven*: it reads `manifest.json` at run
//! time rather than being generated with paths baked in. That means the same
//! script works after the user moves the folder, renames the drive, or restores
//! onto a machine with a different username — and it stays idempotent, so a
//! half-finished restore can simply be re-run.

use crate::error::AppResult;
use crate::manifest::Manifest;
use std::path::{Path, PathBuf};

/// The PowerShell restore driver, embedded at compile time so the binary is
/// self-contained and the bundled resource can't drift from the code.
const RESTORE_TEMPLATE: &str = include_str!("../assets/restore.ps1.tmpl");

pub fn write_script(staging: &Path, manifest: &Manifest) -> AppResult<PathBuf> {
    let path = staging.join("restore.ps1");
    // UTF-8 BOM: Windows PowerShell 5.1 mis-decodes the box-drawing and
    // non-ASCII characters in the here-strings without it.
    let mut out = String::from("\u{feff}");
    out.push_str(&format!(
        "# Generated by rebackup {} on {} for {}\\{}\n\
         # Manifest version {}, {} file(s), {} sealed artifact(s).\n\n",
        manifest.tool_version,
        manifest.created,
        manifest.machine,
        manifest.user,
        manifest.version,
        manifest.file_count,
        manifest.sealed.len(),
    ));
    out.push_str(RESTORE_TEMPLATE);
    std::fs::write(&path, out)?;

    // A one-line launcher, because double-clicking a .ps1 opens Notepad.
    let cmd = staging.join("restore.cmd");
    std::fs::write(
        &cmd,
        "@echo off\r\n\
         powershell.exe -NoProfile -ExecutionPolicy Bypass -File \"%~dp0restore.ps1\" %*\r\n\
         pause\r\n",
    )?;

    Ok(path)
}

/// Readme dropped next to the backup so it makes sense a month later.
pub fn write_readme(staging: &Path, manifest: &Manifest) -> AppResult<PathBuf> {
    let path = staging.join("READ-ME-FIRST.txt");
    let body = format!(
        "PRE-RESET BACKUP\n\
         ================\n\n\
         Created : {}\n\
         Machine : {} ({})\n\
         Windows : {}\n\
         Files   : {} ({} bytes)\n\
         Sealed  : {} encrypted artifact(s)\n\n\
         WHAT TO DO\n\
         ----------\n\
         1. Copy this ENTIRE folder to an external drive before you reset.\n\
         2. After the clean install, run restore.cmd (or restore.ps1) from here.\n\
         3. Use -DryRun first if you want to see what it would do.\n\n\
         PASSPHRASE\n\
         ----------\n\
         Files ending in .rbu are encrypted with the passphrase you chose.\n\
         There is NO recovery if you lose it. Write it down somewhere that will\n\
         survive the reset -- not on the machine being wiped.\n\n\
         VERIFY\n\
         ------\n\
         Every file's SHA-256 is in manifest.json and was checked after copying.\n\
         Re-check any time with:  rebackup.exe verify --manifest manifest.json\n",
        manifest.created,
        manifest.machine,
        manifest.user,
        manifest.windows_build.as_deref().unwrap_or("unknown"),
        manifest.file_count,
        manifest.total_bytes,
        manifest.sealed.len(),
    );
    std::fs::write(&path, body)?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn writes_a_runnable_pair_of_scripts() {
        let dir = std::env::temp_dir().join(format!("rbu-restore-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let m = Manifest::new(&dir, vec!["desktop".into()]);

        let p = write_script(&dir, &m).unwrap();
        let text = std::fs::read_to_string(&p).unwrap();
        assert!(text.contains("param("));
        assert!(text.contains("manifest.json"));
        assert!(dir.join("restore.cmd").exists());

        write_readme(&dir, &m).unwrap();
        assert!(dir.join("READ-ME-FIRST.txt").exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn template_documents_every_profile_with_manual_steps() {
        for id in [
            "opera-gx",
            "steam",
            "git-repos",
            "windows-credentials",
            "ai-tools",
        ] {
            assert!(
                RESTORE_TEMPLATE.contains(id),
                "restore template has no follow-up section for {id}"
            );
        }
    }
}
